version: '3.7'

services:
    node-docker:
        build:
            context: .
            dockerfile: Dockerfile
            target: production
        volumes:
            - ./src:/home/node/app/src
            - ./nodemon.json:/home/node/app/nodemon.json
        container_name: node-docker
        environment:
            - REDIS_HOST=redis-server
            - HOST=0.0.0.0
            - PORT=8000
        ports:
            - '8000:8000'
        command: node ./build/src/index.js
        depends_on:
            - redis-server
    redis-server:
        image: redis:latest
